name: dynamic_library
description: Dart library for improving the process of loading dynamic libraries (with OS-specific load checks) and initializing Flutter Rust Bridge packages.
version: 1.0.0
homepage: https://github.com/open-runtime/dynamic_library

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter_rust_bridge: ^2.9.0
  path: ^1.8.0

dev_dependencies:
  runtime_lints: ^0.3.0
  test: ^1.25.0
